isi:
  -
    gambar: roti durian keju.jpg
    judul: Roti Durian Keju
    harga_awal: 50000
    harga: 34000
  -
    gambar: roti durian original.jpg
    judul: Roti Durian Original
    harga: 30000
  -
    gambar: roti durian keju.jpg
    judul: Roti Durian Keju
    harga: 34000
  -
    gambar: roti durian original.jpg
    judul: Roti Durian Original
    harga: 30000
  -
    gambar: roti durian keju.jpg
    judul: Roti Durian Keju
    harga: 34000
  -
    gambar: roti durian original.jpg
    judul: Roti Durian Original
    harga: 30000
  -
    gambar: roti durian keju.jpg
    judul: Roti Durian Keju
    harga: 34000
  -
    gambar: roti durian original.jpg
    judul: Roti Durian Original
    harga: 30000